app:
  services:
    profile: http://localhost:8085/profile
openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080
    title: API Service
    version: 1.0.0
spring:
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: relationshipService
  data:
    mongodb:
       url: mongodb://localhost:27017/relationship_db
       database: relationship_db
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /relationship
    session:
      timeout: 3m
  port: 8088

logging:
  level:
    org.springframework: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    org.hibernate.event.internal.AbstractFlushingEventListener: DEBUG
