services:
  # Account Service
  accountservice:
    build:
      context: accountService
      dockerfile: Dockerfile
    container_name: ${ACCOUNT_SERVICE}
    restart: always
    image: ${ACCOUNT_SERVICE}
    environment:
      - PROFILE_SERVICE_URL=${PROFILE_SERVICE_URL}
      - EMAIL_APP=${EMAIL_APP}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - MYSQL_URL=${MYSQL_URL}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CONTAINER=${REDIS_CONTAINER}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - RESEND_MAIL_FROM=${RESEND_MAIL_FROM}
      - RESEND_HOST=${RESEND_HOST}
      - RESEND_PORT=${RESEND_PORT}
      - RESEND_NAME=${RESEND_NAME}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - FRONT_END=${FRONT_END}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    ports:
      - "${ACCOUNT_PORT}:${ACCOUNT_PORT}" 
    networks:
      - app_network

  # Message Service
  messageservice:
    build:
      context: messageService
      dockerfile: Dockerfile
    container_name: ${MESSAGE_SERVICE}
    restart: always
    image: ${MESSAGE_SERVICE}
    environment:
      - MONGODB_MESSAGE_URL=${MONGODB_MESSAGE_URL}
      - REDIS_USER=${REDIS_USER}
      - REDIS_CONTAINER=${REDIS_CONTAINER}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - PROFILE_SERVICE_URL=${PROFILE_SERVICE_URL}
      - ACCOUNT_SERVICE_URL=${ACCOUNT_SERVICE_URL}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    ports:
      - "${MESSAGE_PORT}:${MESSAGE_PORT}"
    networks:
      - app_network

  # Notification Service
  notificationservice:
    build:
      context: notificationService
      dockerfile: Dockerfile
    container_name: ${NOTIFICATION_SERVICE}
    restart: always
    image: ${NOTIFICATION_SERVICE}
    environment:
      - PROFILE_SERVICE_URL=${PROFILE_SERVICE_URL}
      - MONGODB_NOTIFICATION_URL=${MONGODB_NOTIFICATION_URL}
      - NOTIFICATION_SERVICE_URL_SOCKET=${NOTIFICATION_SERVICE_URL_SOCKET}
      - REDIS_USER=${REDIS_USER}
      - REDIS_CONTAINER=${REDIS_CONTAINER}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    ports:
      - "${NOTIFICATION_PORT}:${NOTIFICATION_PORT}"
    networks:
      - app_network

  # Post Service
  postservice:
    build:
      context: postService
      dockerfile: Dockerfile
    container_name: ${POST_SERVICE}
    restart: always
    image: ${POST_SERVICE}
    environment:
      - ACCOUNT_SERVICE_URL=${ACCOUNT_SERVICE_URL}
      - PROFILE_SERVICE_URL=${PROFILE_SERVICE_URL}
      - MONGODB_POST_URL=${MONGODB_POST_URL}
      - REDIS_USER=${REDIS_USER}
      - REDIS_CONTAINER=${REDIS_CONTAINER}
      - REDIS_USER=${REDIS_USER}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    ports:
      - "${POST_PORT}:${POST_PORT}"
    networks:
      - app_network

  # Profile Service
  profileservice:
    build:
      context: profileService
      dockerfile: Dockerfile
    container_name: ${PROFILE_SERVICE}
    restart: always
    image: ${PROFILE_SERVICE}
    environment:
      - ACCOUNT_SERVICE_URL=${ACCOUNT_SERVICE_URL}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
      - POST_SERVICE_URL=${POST_SERVICE_URL}
      - NEO4J_URL=${NEO4J_URL}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CONTAINER=${REDIS_CONTAINER}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    ports:
      - "${PROFILE_PORT}:${PROFILE_PORT}"
    networks:
      - app_network

  # API Gateway
  apigateway:
    build:
      context: apigateway
      dockerfile: Dockerfile
    container_name: ${API_GATEWAY}
    image: ${API_GATEWAY}
    restart: always
    environment:
      - SPRING_APPLICATION_ACTIVE=pro
      - GATEWAY_PORT=${GATEWAY_PORT}
      - ACCOUNT_SERVICE_URL=${ACCOUNT_SERVICE_URL}
      - PROFILE_SERVICE_URL=${PROFILE_SERVICE_URL}
      - POST_SERVICE_URL=${POST_SERVICE_URL}
      - MESSAGE_SERVICE_URL=${MESSAGE_SERVICE_URL}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
      - REDIS_USER=${REDIS_USER}
      - REDIS_CONTAINER=${REDIS_CONTAINER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    name: fsocial_network
