spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
  application:
    name: profileService
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  servlet:
    context-path: /profile
    session:
      timeout: 3m
  port: 8085

logging:
  level:
    org.neo4j.driver: ERROR
    org:
      springframework=DEBUG:
      springframework:
        security: DEBUG
        security.web.access.ExceptionTranslationFilter: DEBUG
        security.access.intercept.AbstractSecurityInterceptor: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
        event:
          internal:
            AbstractFlushingEventListener: DEBUG

app:
  services:
    account: http://localhost:8081/account
    post: http://localhost:8083/post

redis:
  host: localhost   # Địa chỉ Redis server
  port: 6379        # Cổng mặc định Redis
  lettuce:
    pool:
      max-active: 10   # Số lượng kết nối tối đa
      max-idle: 5      # Số kết nối tối đa có thể rỗng
      min-idle: 1      # Số kết nối tối thiểu có thể rỗng
  timeout: 2000ms     # Thời gian chờ kết nối Redis