app:
  services:
    profile: http://localhost:8085/profile

spring:
  application:
    name: timelineService
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27002/primary_database?authSource=admin
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true

server:
  servlet:
    context-path: /timeline
    session:
      timeout: 3m
  port: 8086

logging:
  level:
    org:
      springframework=DEBUG:
      springframework:
        security: DEBUG
        security.web.access.ExceptionTranslationFilter: DEBUG
        security.access.intercept.AbstractSecurityInterceptor: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
        event:
          internal:
            AbstractFlushingEventListener: DEBUG