app:
  services:
    profile: http://localhost:8085/profile
    account: http://localhost:8081/account
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  version: 1.0.0
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
openapi:
  service:
    api-docs: post-service
    server: http://localhost:8086
    serverName: TimeLine service
    title: Post Service API
    version: 1.0.0
    description: API for managing timeline
spring:
  application:
    name: timelineService
  data:
    mongodb:
      uri: mongodb://localhost:27017/post_db
      database: post_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true

server:
  servlet:
    context-path: /timeline
    session:
      timeout: 3m
    register-default-servlet: false
  port: 8086
logging:
  level:
    com.cangngo: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.cors: TRACE
    org:
      springframework=DEBUG:
      springframework:
        security: DEBUG
        security.web.access.ExceptionTranslationFilter: DEBUG
        security.access.intercept.AbstractSecurityInterceptor: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
        event:
          internal:
            AbstractFlushingEventListener: DEBUG
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
