server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: account_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/account/**
          filters:
            - StripPrefix=2
        - id: message_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/message/**
          filters:
            - StripPrefix=2
        - id: post_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: processor_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/processor/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/profile/public/**
          filters:
            - StripPrefix=2
        - id: timeline_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/timeline/**
          filters:
            - StripPrefix=2