server:
  port: 8888
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls:
      - name: postservice
        url: /post/api-docs
      - name: timelineservice
        url: /timeline/api-docs
  version: 1.0.0
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
app:
  api-prefix: /api/v1
spring:
  security:
    user:
      name: admin
      password: 12345
  application:
    name: apigateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: account_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/account/**
          filters:
            - StripPrefix=2
        - id: message_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/message/**
          filters:
            - StripPrefix=2
        - id: post_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: processor_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/processor/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: timeline_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/timeline/**
          filters:
            - StripPrefix=2
        - id: notification_service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: relationship_service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/relationship/**
          filters:
            - StripPrefix=2