app:
  services:
    profile: http://localhost:8085/profil
openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080
    title: API Service
    version: 1.0.0
spring:
  application:
    name: postService
  data:
    mongodb:
       uri: mongodb://root:root@localhost:27001/primary_database?authSource=admin
       auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  servlet:
    context-path: /post
    session:
      timeout: 3m
  port: 8083

logging:
  level:
    org:
      springframework=DEBUG:
      springframework:
        security: DEBUG
        security.web.access.ExceptionTranslationFilter: DEBUG
        security.access.intercept.AbstractSecurityInterceptor: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
        event:
          internal:
            AbstractFlushingEventListener: DEBUG
