app:
  services:
    profile: http://localhost:8085/profile
    account: http://localhost:8081/account
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  version: 1.0.0
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
openapi:
  service:
    api-docs: post-service
    server: http://localhost:8083
    serverName: Post service
    title: Post Service API
    version: 1.0.0
    description: API for managing posts
spring:
  application:
    name: post_service
  data:
    mongodb:
       uri: mongodb://localhost:27017/post_db
       database: post_db
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  servlet:
    context-path: /post
    session:
      timeout: 3m
  port: 8083

logging:
  level:
    org.springframework: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    org.hibernate.event.internal.AbstractFlushingEventListener: DEBUG