
spring:
  application:
    name: postService
  data:
    mongodb:
       uri: mongodb://root:root@localhost:27017/post-service?authSource=admin
       auto-index-creation: true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 100MB

server:
  servlet:
    context-path: /post
    session:
      timeout: 3m
  port: 8083

logging:
  level:
    org:
      springframework=DEBUG:
      springframework:
        security: DEBUG
        security.web.access.ExceptionTranslationFilter: DEBUG
        security.access.intercept.AbstractSecurityInterceptor: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
        event:
          internal:
            AbstractFlushingEventListener: DEBUG