app:
  services:
    profile: ${PROFILE_SERVICE_URL}
  validation:
    password-regex: "^(?=.*[A-Za-z])(?=.*\\d).{8,}$"
    password-length: 8 # Độ dài tối thiểu của password
    name-regex: "^[A-Za-zÀ-ỹ\\s]+$"
    age-valid: 18 # Độ tuổi để sử dụng FSocial
spring:
  data:
    redis:
      host: ${REDIS_CONTAINER}  # Vì Redis chạy trên localhost
      port: ${REDIS_PORT}  # Port từ docker-compose (REDIS_PORT từ .env)
      password: ${REDIS_PASSWORD}
      database: 0
      timeout: 2000ms
      connect-timeout: 2000ms
      # Cấu hình connection pool cho Spring Data Redis
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 500ms
        shutdown-timeout: 200ms
  application:
    name: account
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}  # Dùng root tạm thời
    password: ${MYSQL_PASSWORD}  # Password của root
  kafka:
    bootstrap-servers: kafka:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: ${EMAIL_PORT}
    username: ${EMAIL_APP}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /account
    session:
      timeout: 3m
  port: 8081


logging:
  level:
    org:
      springframework=DEBUG:
      springframework:
        security: DEBUG
        security.web.access.ExceptionTranslationFilter: DEBUG
        security.access.intercept.AbstractSecurityInterceptor: DEBUG
        security.web.FilterChainProxy: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
        event:
          internal:
            AbstractFlushingEventListener: DEBUG

jwt:
  signerKey: "q66wYIc6orfW00uGYvH0pJO2TX3fsoFGZEvbpMJNcvGMvqYc7cfI6eTrHTOvulif"
  duration: 1 # Đơn vị là phút
  expired-time: 3 # Đơn vị là ngày

otp:
  expiration:
    send: 5 # Đơn vị là phút
    verify: 10 # Đơn vị là giây