app:
  services:
    profile: http://localhost:8085/profile
  validation:
    password-regex: "^(?=.*[A-Za-z])(?=.*\\d).{8,}$"
    password-length: 8 # Độ dài tối thiểu của password
    name-regex: "^[A-Za-zÀ-ỹ\\s]+$"
    age-valid: 18 # Độ tuổi để sử dụng FSocial
spring:
  application:
    name: accountService
  datasource:
    url: jdbc:mysql://localhost:3306/account_service?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: khaildps37419@fpt.edu.vn
    password: ieww vlfs guvu smgs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

redis:
  host: replica_redis
  port: 6379
  database: 0
  timeout: 10s
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 500ms
    shutdown-timeout: 200ms   # Thời gian chờ kết nối Redis


server:
  servlet:
    context-path: /account
    session:
      timeout: 3m
  port: 8081


logging:
  level:
    org:
      springframework=DEBUG:
      springframework:
        security: DEBUG
        security.web.access.ExceptionTranslationFilter: DEBUG
        security.access.intercept.AbstractSecurityInterceptor: DEBUG
        security.web.FilterChainProxy: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
        event:
          internal:
            AbstractFlushingEventListener: DEBUG

jwt:
  signerKey: "q66wYIc6orfW00uGYvH0pJO2TX3fsoFGZEvbpMJNcvGMvqYc7cfI6eTrHTOvulif"
  duration: 1 # Đơn vị là phút
  expired-time: 3 # Đơn vị là ngày

otp:
  expiration:
    send: 5 # Đơn vị là phút
    verify: 10 # Đơn vị là giây