app:
  services:
    profile: http://localhost:8085/profile
spring:
  application:
    name: accountService
  datasource:
    url: jdbc:mysql://localhost:3306/account_service?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: khaildps37419@fpt.edu.vn
    password: mxzx aacu asud keyh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost   # Địa chỉ Redis server
    port: 6379        # Cổng mặc định Redis
    lettuce:
      pool:
        max-active: 10   # Số lượng kết nối tối đa
        max-idle: 5      # Số kết nối tối đa có thể rỗng
        min-idle: 1      # Số kết nối tối thiểu có thể rỗng
    timeout: 2000ms     # Thời gian chờ kết nối Redis

server:
  servlet:
    context-path: /account
    session:
      timeout: 3m
  port: 8081


logging:
  level:
    org:
      springframework=DEBUG:
      springframework:
        security: DEBUG
        security.web.access.ExceptionTranslationFilter: DEBUG
        security.access.intercept.AbstractSecurityInterceptor: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
        event:
          internal:
            AbstractFlushingEventListener: DEBUG

jwt:
  signerKey: "R/iERv2snkyWEnD1l8zllBu9JGpBpnfO7UcOLvo0htPGU7xoDyGB3QksYid+G7"