app:
  services:
    profile: ${PROFILE_SERVICE_URL:http://localhost:8085}/profile
    account: ${ACCOUNT_SERVICE_URL:http://localhost:8081}/account
spring:
  application:
    name: messageService
  data:
    mongodb:
      uri: ${MONGODB_MESSAGE_URL:mongodb://admin:adminpassword@localhost:27017/message_db?authSource=admin}
      database: message_db
    redis:
      host: ${REDIS_CONTAINER:localhost}  # Vì Redis chạy trên localhost
      port: ${REDIS_PORT:6379}  # Port từ docker-compose (REDIS_PORT từ .env)
      password: ${REDIS_PASSWORD:redispassword}
      database: 0
      timeout: 2000ms
      connect-timeout: 2000ms
      # Cấu hình connection pool cho Spring Data Redis
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 500ms
        shutdown-timeout: 200ms
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
server:
  servlet:
    context-path: /message
    session:
      timeout: 3m
  port: 8082

logging:
  level:
    org:
      springframework=DEBUG:
      springframework:
        security: DEBUG
        security.web.access.ExceptionTranslationFilter: DEBUG
        security.access.intercept.AbstractSecurityInterceptor: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        engine:
          transaction:
            internal:
              TransactionImpl: DEBUG
        event:
          internal:
            AbstractFlushingEventListener: DEBUG
